[package]
name = "mdok-test-server"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "test-server"
path = "src/main.rs"

[dependencies]
base64.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
flate2 = "1"
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
rustls-pemfile = "2"
rustls-pki-types = "1"
sha2 = "0.10"
