[package]
name = "mdok-quickjs"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
base64.workspace = true
mdok-curl = { path = "../mdok-curl" }
percent-encoding.workspace = true
reqwest.workspace = true
rquickjs = { version = "0.12", features = ["macro"] }
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
thiserror.workspace = true
