#!/usr/bin/env python3
"""MCP stdio conformance suite for the mdok MCP server.

Black-box wire-protocol tests: the runner starts `<server> mcp serve` inside
an isolated temporary workspace assembled from `tests/mcp/` fixtures plus a
generated operator `mdok.toml`, then drives it with newline-delimited
JSON-RPC 2.0 and asserts the contract documented in `docs/MCP.md`:

- initialize handshake and server metadata
- exact tool inventory with descriptions and input schemas
- document tools (lint/plan/list/test) re-exec the CLI and wrap its JSON
- probe sandbox validation, budget clamping (F7), and offline execution
- Postman import input validation and read-root confinement (F9)
- operator-policy invariants (F5): client `config` is ignored, secrets stay
  out of child argv, client allow/deny lists may only narrow

The suite is binary-agnostic on purpose: any re-implementation of the mdok
MCP surface (for example a Go port) is gated by the identical suite.

Deterministic, offline (loopback-free), Python stdlib only.

Usage:
    python3 scripts/run_mcp_conformance.py [--server target/debug/mdok]
"""

from __future__ import annotations

import argparse
import json
import os
import select
import shutil
import subprocess
import sys
import tempfile
import threading
import time
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
FIXTURES = ROOT / "tests" / "mcp"
DEFAULT_SERVER = ROOT / "target" / "debug" / "mdok"

PROTOCOL_VERSION = "2025-06-18"
CLIENT_INFO = {"name": "mdok-conformance", "version": "1"}
REQUEST_TIMEOUT_SECONDS = 120.0
SESSION_DEADLINE_SECONDS = 600.0

EXPECTED_TOOLS = [
    "mdok_test",
    "mdok_lint",
    "mdok_plan",
    "mdok_list",
    "mdok_probe",
    "mdok_import_postman",
    "mdok_version",
]

OPERATOR_CONFIG_TEMPLATE = """\
# Generated by scripts/run_mcp_conformance.py; operator policy under test.
[policy]
allowed_hosts = ["api.example.test"]
denied_hosts = ["denied.example.invalid"]

[policy.exec]
enabled = true

[policy.exec.commands.mdok-conformance-fixture]
program = "{fixture_program}"
"""


class ConformanceError(AssertionError):
    """A conformance assertion failed, with the observed value attached."""


def expect(condition: Any, message: str, actual: Any = None) -> None:
    if not condition:
        raise ConformanceError(f"{message} (observed: {json.dumps(actual, default=str)[:400]})")


class McpSession:
    """Minimal stdio JSON-RPC 2.0 client for one server process."""

    def __init__(self, server: Path, cwd: Path, stderr_path: Path) -> None:
        self.stderr_file = stderr_path.open("w", encoding="utf-8")
        self.process = subprocess.Popen(
            [str(server), "mcp", "serve"],
            cwd=str(cwd),
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=self.stderr_file,
            text=True,
            bufsize=1,
        )
        self._next_id = 0
        self._deadline = time.monotonic() + SESSION_DEADLINE_SECONDS
        self._watchdog = threading.Timer(SESSION_DEADLINE_SECONDS, self._kill)
        self._watchdog.daemon = True
        self._watchdog.start()

    def _kill(self) -> None:
        if self.process.poll() is None:
            self.process.kill()

    def _read_message(self, timeout: float) -> dict[str, Any] | None:
        deadline = time.monotonic() + timeout
        while True:
            remaining = deadline - time.monotonic()
            if remaining <= 0 or self.process.poll() is not None:
                return None
            ready, _, _ = select.select([self.process.stdout], [], [], min(remaining, 0.5))
            if not ready:
                continue
            line = self.process.stdout.readline()
            if not line.strip():
                continue
            try:
                message = json.loads(line)
            except json.JSONDecodeError:
                continue
            if isinstance(message, dict):
                return message

    def request(
        self, method: str, params: dict[str, Any] | None = None, timeout: float = REQUEST_TIMEOUT_SECONDS
    ) -> dict[str, Any]:
        self._next_id += 1
        request_id = self._next_id
        frame = {"jsonrpc": "2.0", "id": request_id, "method": method}
        if params is not None:
            frame["params"] = params
        self.process.stdin.write(json.dumps(frame) + "\n")
        self.process.stdin.flush()
        while True:
            message = self._read_message(timeout)
            expect(message is not None, f"no response to {method} before timeout", None)
            assert message is not None
            if message.get("id") != request_id:
                continue
            return message

    def notify(self, method: str, params: dict[str, Any] | None = None) -> None:
        frame: dict[str, Any] = {"jsonrpc": "2.0", "method": method}
        if params is not None:
            frame["params"] = params
        self.process.stdin.write(json.dumps(frame) + "\n")
        self.process.stdin.flush()

    def close(self) -> None:
        self._watchdog.cancel()
        if self.process.poll() is None:
            try:
                self.process.stdin.close()
                self.process.wait(timeout=10)
            except Exception:
                self._kill()
        self.stderr_file.close()


def tool_text(response: dict[str, Any]) -> str:
    result = response.get("result", {})
    content = result.get("content", [])
    expect(
        isinstance(content, list) and content and content[0].get("type") == "text",
        "tool response should carry a text content block",
        response,
    )
    return content[0].get("text", "")


def call_tool(session: McpSession, name: str, arguments: dict[str, Any] | None = None) -> dict[str, Any]:
    return session.request("tools/call", {"name": name, "arguments": arguments or {}})


def tool_json(session: McpSession, name: str, arguments: dict[str, Any] | None = None) -> Any:
    """Call a tool expected to succeed and return its decoded JSON payload."""
    response = call_tool(session, name, arguments)
    expect(not response.get("result", {}).get("isError"), f"{name} returned isError", response)
    return json.loads(tool_text(response))


def tool_error_text(session: McpSession, name: str, arguments: dict[str, Any] | None = None) -> str:
    """Call a tool expected to fail and return its error text."""
    response = call_tool(session, name, arguments)
    expect(response.get("result", {}).get("isError"), f"{name} should report isError", response)
    return tool_text(response)


def document_arguments(path: str, **overrides: Any) -> dict[str, Any]:
    arguments: dict[str, Any] = {"paths": [path], "offline": True}
    arguments.update(overrides)
    return arguments


# --- Cases -------------------------------------------------------------------


def case_initialize(session: McpSession) -> None:
    response = session.request(
        "initialize",
        {"protocolVersion": PROTOCOL_VERSION, "capabilities": {}, "clientInfo": CLIENT_INFO},
        timeout=30,
    )
    result = response.get("result")
    expect(isinstance(result, dict), "initialize should return a result object", response)
    assert isinstance(result, dict)
    expect(
        isinstance(result.get("protocolVersion"), str) and result["protocolVersion"],
        "initialize should negotiate a protocol version",
        result,
    )
    info = result.get("serverInfo", {})
    expect(info.get("name") == "mdok", "serverInfo.name should be mdok", info)
    expect(
        isinstance(result.get("capabilities", {}).get("tools"), (dict, bool)),
        "capabilities should advertise tools",
        result.get("capabilities"),
    )
    session.notify("notifications/initialized")


def case_unknown_method(session: McpSession) -> None:
    response = session.request("bogus/nonexistent", {})
    expect("error" in response, "unknown method should return a JSON-RPC error", response)
    expect(response.get("error", {}).get("code") == -32601, "unknown method should be -32601", response)


def case_tool_inventory(session: McpSession) -> None:
    response = session.request("tools/list", {})
    tools = response.get("result", {}).get("tools", [])
    names = sorted(tool.get("name", "") for tool in tools)
    expect(names == sorted(EXPECTED_TOOLS), "tool inventory mismatch", names)
    for tool in tools:
        expect(bool(tool.get("description")), f"{tool.get('name')} needs a description", tool)
        schema = tool.get("inputSchema")
        expect(isinstance(schema, dict) and schema.get("type") == "object",
               f"{tool.get('name')} needs an object inputSchema", schema)


def case_version(session: McpSession) -> None:
    payload = tool_json(session, "mdok_version")
    for key in ("mdok_version", "curl_version", "libcurl", "tls", "postman_profile"):
        expect(key in payload, f"mdok_version should include {key}", payload)
    expect(payload.get("mcp") is True, "mdok_version should set mcp=true", payload)


def case_document_lint(session: McpSession) -> None:
    payload = tool_json(session, "mdok_lint", document_arguments("health.md"))
    expect(payload.get("operation") == "lint", "operation should echo lint", payload)
    expect(payload.get("ok") is True, "lint of health.md should succeed", payload)
    result = payload.get("result", {})
    expect(result.get("schema_version"), "lint report needs schema_version", result)


def case_document_plan(session: McpSession) -> None:
    payload = tool_json(session, "mdok_plan", document_arguments("health.md"))
    expect(payload.get("ok") is True, "plan of health.md should succeed", payload)
    expect(isinstance(payload.get("result"), dict), "plan should return a JSON object", payload)


def case_document_list(session: McpSession) -> None:
    payload = tool_json(session, "mdok_list", document_arguments("health.md"))
    expect(payload.get("ok") is True, "list of health.md should succeed", payload)
    text = json.dumps(payload)
    expect("health" in text, "list output should mention the health step", payload)


def case_document_test_pass(session: McpSession) -> None:
    # offline=True would reject the exec step (MDOK-E302), so run online;
    # the exec profile itself touches no network.
    arguments = document_arguments("exec.md")
    arguments["offline"] = False
    payload = tool_json(session, "mdok_test", arguments)
    expect(payload.get("ok") is True, "test of exec.md should succeed", payload)


def case_document_test_denied(session: McpSession) -> None:
    payload = tool_json(session, "mdok_test", document_arguments("denied.md"))
    expect(payload.get("ok") is False, "test of denied.md should fail", payload)
    text = json.dumps(payload)
    expect("MDOK-E" in text, "denied run should surface an MDOK-E diagnostic", payload)


def case_document_missing_path(session: McpSession) -> None:
    payload = tool_json(session, "mdok_lint", document_arguments("does-not-exist.md"))
    expect(payload.get("ok") is False, "lint of a missing file should fail", payload)


def case_empty_paths_rejected(session: McpSession) -> None:
    message = tool_error_text(session, "mdok_test", {"paths": []})
    expect("paths" in message, "empty paths error should mention paths", message)


def case_invalid_variable_name(session: McpSession) -> None:
    message = tool_error_text(
        session, "mdok_lint", document_arguments("health.md", vars={"1bad": "x"})
    )
    expect("invalid variable name" in message, "bad var name should be rejected", message)


def case_secrets_never_in_response(session: McpSession) -> None:
    secret_value = "conformance-secret-value-9f2c"
    response = call_tool(
        session,
        "mdok_test",
        document_arguments("denied.md", secrets={"TOKEN": secret_value}),
    )
    text = json.dumps(response)
    expect(secret_value not in text, "secret value must never appear in tool output", "redacted")
    expect(
        "conformance-secret" not in text.lower(),
        "secret value fragments must not appear in tool output",
        "redacted",
    )


def case_client_config_ignored(session: McpSession) -> None:
    """F5: a client-supplied config path must never replace the operator's."""
    payload = tool_json(
        session,
        "mdok_lint",
        document_arguments("health.md", config="/nonexistent/mdok.toml"),
    )
    expect(payload.get("ok") is True, "client config must be ignored, not honored", payload)


def case_probe_offline(session: McpSession) -> None:
    payload = tool_json(
        session,
        "mdok_probe",
        {
            "script": "pm.test('status is 200', function () { pm.expect(200).to.eql(200); });",
            "phase": "test",
        },
    )
    expect(isinstance(payload, dict), "probe should return an object", payload)


def case_probe_invalid_network(session: McpSession) -> None:
    message = tool_error_text(
        session, "mdok_probe", {"script": "1", "network": "internet"}
    )
    expect("network" in message, "invalid network should be rejected", message)


def case_probe_timeout_bounds(session: McpSession) -> None:
    for timeout_ms in (0, 60001):
        message = tool_error_text(
            session, "mdok_probe", {"script": "1", "timeout_ms": timeout_ms}
        )
        expect("timeout" in message.lower(), f"timeout_ms={timeout_ms} should be rejected", message)


def case_probe_budgets_clamp_down(session: McpSession) -> None:
    """F7: oversized client budgets clamp to server defaults instead of erroring."""
    payload = tool_json(
        session,
        "mdok_probe",
        {
            "script": "pm.test('clamp', function () { pm.expect(1).to.eql(1); });",
            "profile": {"max_memory_bytes": 1099511627776},
        },
    )
    expect(isinstance(payload, dict), "probe with huge budget should still run", payload)


def case_import_inline_collection(session: McpSession) -> None:
    collection = (FIXTURES / "postman-minimal.json").read_text(encoding="utf-8")
    payload = tool_json(session, "mdok_import_postman", {"collection_json": collection})
    for key in ("ok", "requires_review", "markdown", "manifest"):
        expect(key in payload, f"import result should include {key}", payload)
    expect("curl" in payload.get("markdown", ""), "markdown should contain a curl fence", payload)


def case_import_input_validation(session: McpSession) -> None:
    collection = (FIXTURES / "postman-minimal.json").read_text(encoding="utf-8")
    message = tool_error_text(
        session,
        "mdok_import_postman",
        {"collection_json": collection, "path": "postman-minimal.json"},
    )
    expect("not both" in message or "both" in message, "json+path should be rejected", message)
    message = tool_error_text(session, "mdok_import_postman", {})
    expect("required" in message, "missing input should be rejected", message)


def case_import_read_root_confinement(session: McpSession) -> None:
    """F9: import paths are confined to the server working directory."""
    message = tool_error_text(session, "mdok_import_postman", {"path": "/etc/hosts"})
    expect("roots" in message, "out-of-root import should be rejected", message)


def case_unknown_tool(session: McpSession) -> None:
    response = call_tool(session, "mdok_nope", {})
    failed = response.get("result", {}).get("isError") or "error" in response
    expect(failed, "unknown tool should not succeed", response)


CASES = [
    ("initialize handshake", case_initialize),
    ("unknown method -> JSON-RPC error", case_unknown_method),
    ("tool inventory and schemas", case_tool_inventory),
    ("mdok_version payload", case_version),
    ("mdok_lint document", case_document_lint),
    ("mdok_plan document", case_document_plan),
    ("mdok_list document", case_document_list),
    ("mdok_test passing document", case_document_test_pass),
    ("mdok_test denied host fails with diagnostic", case_document_test_denied),
    ("mdok_lint missing file fails", case_document_missing_path),
    ("empty paths rejected", case_empty_paths_rejected),
    ("invalid variable name rejected", case_invalid_variable_name),
    ("secrets never leak into responses", case_secrets_never_in_response),
    ("client config ignored (F5)", case_client_config_ignored),
    ("mdok_probe offline", case_probe_offline),
    ("mdok_probe invalid network", case_probe_invalid_network),
    ("mdok_probe timeout bounds", case_probe_timeout_bounds),
    ("mdok_probe budgets clamp down (F7)", case_probe_budgets_clamp_down),
    ("mdok_import_postman inline", case_import_inline_collection),
    ("mdok_import_postman input validation", case_import_input_validation),
    ("mdok_import_postman read-root confinement (F9)", case_import_read_root_confinement),
    ("unknown tool fails", case_unknown_tool),
]


def build_workspace(directory: Path, fixture_program: Path) -> Path:
    workspace = directory / "workspace"
    workspace.mkdir()
    config = OPERATOR_CONFIG_TEMPLATE.format(fixture_program=fixture_program.resolve())
    (workspace / "mdok.toml").write_text(config, encoding="utf-8")
    for name in ("health.md", "exec.md", "denied.md"):
        shutil.copy2(FIXTURES / name, workspace / name)
    return workspace


def find_server(server: Path) -> Path:
    if server.is_file():
        return server.resolve()
    raise SystemExit(f"server binary not found: {server} (build with `cargo build -p mdok-cli`)")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--server", type=Path, default=DEFAULT_SERVER, help="mdok binary to test")
    parser.add_argument(
        "--fixture",
        type=Path,
        default=ROOT / "target" / "debug" / "mdok-command-fixture",
        help="mdok-command-fixture binary used by the exec profile",
    )
    args = parser.parse_args()
    server = find_server(args.server)
    if not args.fixture.is_file():
        raise SystemExit(f"fixture binary not found: {args.fixture}")

    passed = 0
    failed = 0
    with tempfile.TemporaryDirectory(prefix="mdok-mcp-conformance-") as raw:
        directory = Path(raw)
        workspace = build_workspace(directory, args.fixture)
        stderr_path = directory / "server.stderr"
        session = McpSession(server, workspace, stderr_path)
        try:
            for name, case in CASES:
                try:
                    case(session)
                    print(f"PASS {name}")
                    passed += 1
                except ConformanceError as error:
                    print(f"FAIL {name}: {error}")
                    failed += 1
                except Exception as error:  # transport died mid-session
                    print(f"FAIL {name}: unexpected {type(error).__name__}: {error}")
                    failed += 1
                    break
        finally:
            session.close()
        if failed:
            tail = subprocess.run(
                ["tail", "-n", "20", str(stderr_path)], capture_output=True, text=True
            )
            if tail.stdout.strip():
                print("--- server stderr (tail) ---")
                print(tail.stdout.strip())

    print(f"mcp conformance: {passed}/{passed + failed} passed")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
